name: Publish VSCode Extention to Marketplace
on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release Type'
        required: true
        type: choice
        default: 'patch'
        options:
          - 'patch'
          - 'major'
          - 'minor'
jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Create Changelog
        run: |
          git log $(git describe --tags --abbrev=0)..HEAD --oneline &> ${{ github.workspace }}-CHANGELOG.txt
          cat ${{ github.workspace }}-CHANGELOG.txt
      - name: Setup Git
        run: |
          git config --global user.name "Ashutosh Tripathi"
          git config --global user.email "admin@godspeed.systems"
      - name: Get Current Version Number
        run: |
          CURRENT_VERSION=$(cat package.json | jq .version | cut -d'"' -f 2)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
      - name: Compile New Version
        run: |
          RELEASE_VERSION=$(npx semver $CURRENT_VERSION -i github.event.inputs.releaseType)
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "Bump to $RELEASE_VERSION"
      - name: Version Package
        run: |
          npm version $RELEASE_VERSION
          git tag -a $RELEASE_VERSION -m "$RELEASE_VERSION"
      - name: Package Extension
        run: npx vsce package $RELEASE_VERSION --no-yarn --no-git-tag-version --no-update-package-json -o "./godspeed-$RELEASE_VERSION.vsix"
      - name: Publish to Visual Studio Marketplace
        run: npx vsce publish --packagePath "./godspeed-$RELEASE_VERSION.vsix" --no-yarn --no-git-tag-version --no-update-package-json -p ${{ secrets.VSC_MKTP_PAT }}
      - name: Push Tags
        run: |
          git log -1 --stat
          git remote set-url origin https://${{ secrets.AT_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin main --tags
      - name: Export GIT_TAG
        run: |
          export GIT_TAG=$(git describe --tags --abbrev=0)
          echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV
      - name: GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: './godspeed-*'
          bodyFile: ${{ github.workspace }}-CHANGELOG.txt
          tag: ${{ env.GIT_TAG }}
